FROM node:10
LABEL maintainer Govind_Kulkarni(kulkarnigovind9@gmail.com)
COPY ./ /app
WORKDIR /app
RUN npm -v
RUN nodejs -v
RUN npm install
RUN npm install -g @angular/cli
RUN ng build --prod

FROM nginx
RUN mkdir /app
WORKDIR /app
COPY --from=0 /app/dist/beerbank/. /app
COPY nginx.conf /etc/nginx/nginx.conf
