kind: Service
apiVersion: v1
metadata:
  name:  turing-angular-service
  # annotations:
  #   service.beta.kubernetes.io/aws-load-balancer-additional-resource-tags: "Name=turing-angular-k8s"
  #   service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "443"
  #   service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:us-east-1:321924370566:certificate/62d8ab76-6373-4888-afba-3ca2aea4ba77"
  #   service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
spec:
  selector:
    app:  turing-angular
  type:  NodePort
  ports:
  - name:  http-port
    port:  80
    targetPort:  80
  - name:  https-port
    port:  443
    targetPort:  80